// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDgkQyCe9y6bocXQqTXLybUjSMiOFkjBs',
    appId: '1:1039427654718:web:cc573a08e0f96d1fb5ad6f',
    messagingSenderId: '1039427654718',
    projectId: 'vehicle-maintenance-app-b7c20',
    authDomain: 'vehicle-maintenance-app-b7c20.firebaseapp.com',
    storageBucket: 'vehicle-maintenance-app-b7c20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq4jTI8JKq2M3F952qz2w8CXl_PoaqH4s',
    appId: '1:1039427654718:android:64b7651de918777eb5ad6f',
    messagingSenderId: '1039427654718',
    projectId: 'vehicle-maintenance-app-b7c20',
    storageBucket: 'vehicle-maintenance-app-b7c20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW8vjX99QpBp1rrclGZ3ggVQrKsRntfnI',
    appId: '1:1039427654718:ios:83a595aa0fb8582cb5ad6f',
    messagingSenderId: '1039427654718',
    projectId: 'vehicle-maintenance-app-b7c20',
    storageBucket: 'vehicle-maintenance-app-b7c20.firebasestorage.app',
    iosBundleId: 'com.example.vehicleMaintenanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW8vjX99QpBp1rrclGZ3ggVQrKsRntfnI',
    appId: '1:1039427654718:ios:83a595aa0fb8582cb5ad6f',
    messagingSenderId: '1039427654718',
    projectId: 'vehicle-maintenance-app-b7c20',
    storageBucket: 'vehicle-maintenance-app-b7c20.firebasestorage.app',
    iosBundleId: 'com.example.vehicleMaintenanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDgkQyCe9y6bocXQqTXLybUjSMiOFkjBs',
    appId: '1:1039427654718:web:5d7a5093ecd067b7b5ad6f',
    messagingSenderId: '1039427654718',
    projectId: 'vehicle-maintenance-app-b7c20',
    authDomain: 'vehicle-maintenance-app-b7c20.firebaseapp.com',
    storageBucket: 'vehicle-maintenance-app-b7c20.firebasestorage.app',
  );
}
